const PekFullData = {
  'createdBy': '',
  'createdDate': '',
  'modifiedBy': '',
  'modifiedDate': '',
  'id': '',
  'projectId': '',
  'brands': '',
  'color': '',
  'model': '',
  'shape': '',
  'size': '',
  'grossWeight': '',
  'btyCount': '',
  'netWeight': '',
  'type1': 1,
  'type2': 0,
  'otherDescribe': '',
  'otherDescribeChecked': '',
  'otherDescribeCAddition': '',
  'otherDescribeEAddition': '',
  'inspectionItem1': 1,
  'inspectionItem1Text1': '',
  'inspectionItem1Text2': '',
  'inspectionItem1Text3': '',
  'inspectionItem1Text4': '',
  'inspectionItem2': 1,
  'inspectionItem2Text1': '',
  'inspectionItem2Text2': '',
  'inspectionItem3': 1,
  'inspectionItem3Text1': '',
  'inspectionItem4': 1,
  'inspectionItem4Text1': '',
  'inspectionItem5': 0,
  'inspectionItem5Text1': '',
  'inspectionItem6': 0,
  'result1': '',
  'packPassengerCargo': '',
  'packSubDanger': '',
  'packCargo': '',
  'packSpecial': '',
  'remarks': '',
  'projectNo': '',
  'principalName': null,
  'itemCName': '',
  'itemEName': '',
  'checkLocation': '',
  'checkLocationName': '',
  'appraiser': '',
  'appraiserName': '',
  'appraiseDate': '',
  'according': '',
  'conclusions': 0,
  'unno': '',
  'psn': '',
  'classOrDiv': '',
  'pg': '',
  'checked': false,
  'checker': null,
  'checkerName': null,
  'checkDate': null,
  'editStatus': 0,
  'market': ''
}

const SekFullData = {
  'according': '',
  'appraiseDate': '',
  'appraiser': '',
  'appraiserName': '',
  'btyBrand': '',
  'btyColor': '',
  'btyCount': '',
  'btyCountChecked': '',
  'btyGrossWeight': '',
  'btyGrossWeightChecked': '',
  'btyKind': '',
  'btyNetWeight': '',
  'btyNetWeightChecked': '',
  'btyShape': '',
  'btySize': '',
  'btyType': '',
  'checkDate': 1725614365000,
  'checked': false,
  'checker': '',
  'checkerName': '',
  'checkLocation': '',
  'checkLocationName': '',
  'classOrDiv': '',
  'comment': '',
  'commentExtra': '',
  'conclusions': 0,
  'createdBy': '',
  'createdDate': '',
  'editStatus': 3,
  'id': '',
  'inspectionItem1': '',
  'inspectionItem1Text1': '',
  'inspectionItem1Text2': '',
  'inspectionItem2': '',
  'inspectionItem3': '',
  'inspectionItem4': '',
  'inspectionItem5': '',
  'inspectionItem6': '',
  'inspectionItem7': '',
  'inspectionItem8Cn': '',
  'inspectionItem8En': '',
  'inspectionItem9Cn': '',
  'inspectionItem9En': '',
  'inspectionResult1': '',
  'inspectionResult2': '',
  'inspectionResult3': '',
  'inspectionResult4': '',
  'inspectionResult5': '',
  'inspectionResult6': '',
  'inspectionResult7': '',
  'inspectionResult8': '',
  'inspectionResult9': '',
  'itemCName': '',
  'itemEName': '',
  'market': '',
  'modifiedBy': '',
  'modifiedDate': '',
  'otherDescribe': '',
  'otherDescribeCAddition': '',
  'otherDescribeChecked': '',
  'otherDescribeEAddition': '',
  'pg': '',
  'principalName': null,
  'projectId': '',
  'projectNo': '',
  'psn': '',
  'remarks': '',
  'unno': ''
}

const PekTypeTransMap = [
  'type1',
  'type2',
  'inspectionItem1',
  'inspectionItem2',
  'inspectionItem3',
  'inspectionItem4',
  'inspectionItem5',
  'inspectionItem6',
  'conclusions',
]

const SekTypeTransMap = [
  'conclusions',
]

export {
  PekFullData,
  SekFullData,
  PekTypeTransMap,
  SekTypeTransMap,
}