name: lims-release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: lims

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
        env:
          DISABLE_V8_COMPILE_CACHE: 1
      - name: Install dependencies
        run: |
          npm install
          npm install -g web-ext
      - name: Build
        run: npm run build
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"
      - name: zip chrome extension
        run: |
          mv dist/js/wasm docs/wasm
          mv dist/manifest.wasm.json docs/manifest.wasm.json
          mv dist/manifest.firefox.json docs/manifest.firefox.json
          zip -q -r lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip dist
      - name: zip firefox extension
        run: |
          rm -f dist/manifest.json
          mv docs/manifest.firefox.json dist/manifest.json
          web-ext sign --api-key ${{ secrets.FIREFOX_JWT_ISSUER }} --api-secret ${{ secrets.FIREFOX_JWT_SECRET }} --channel unlisted -s dist
          mv web-ext-artifacts/*.xpi lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
      - name: zip wasm extension
        run: |
          mv docs/manifest.wasm.json dist/manifest.json
          mv docs/wasm dist/js/wasm
          zip -q -r lims-${{ steps.get_version.outputs.VERSION }}.wasm.zip dist
          ls -lh
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lims/lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip
            lims/lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
            lims/lims-${{ steps.get_version.outputs.VERSION }}.wasm.zip
          name: 'Lims ${{ steps.get_version.outputs.VERSION }}'