name: Release and deploy

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write

defaults:
  run:
    working-directory: .

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
        env:
          DISABLE_V8_COMPILE_CACHE: 1
      - name: Install dependencies
        run: |
          npm install
          npm install -g web-ext
      - name: Build
        run: |
          npm run build
          npm run build:firefox
      
      - name: Build docs
        run: |
          npm run docs:build

      - name: Deploy Docs 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/.vitepress/dist

      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:10}"
          echo ::set-output name=version::"${GITHUB_REF:10}"
      - name: zip chrome extension
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          zip -q -r lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip .output/chrome-mv3
      - name: zip firefox extension
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          web-ext sign --api-key ${{ secrets.FIREFOX_JWT_ISSUER }} --api-secret ${{ secrets.FIREFOX_JWT_SECRET }} --channel unlisted -s .output/firefox-mv3
          mv web-ext-artifacts/*.xpi lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            lims-${{ steps.get_version.outputs.VERSION }}.chrome.zip
            lims-${{ steps.get_version.outputs.VERSION }}.firefox.xpi
          name: 'Lims ${{ steps.get_version.outputs.VERSION }}'